### PR TITLE
encoded multisend tx

### PR DESCRIPTION
**Pull request by auryn-macmillan**
Fixes multisig encoding, maybe?

### CODE REVIEW

**Comment by auryn-macmillan** [comment]
recheck

**Comment by auryn-macmillan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by auryn-macmillan** [comment]
@cristovaoth, this should work propoerlly now.

**Review by asgeir-s — APPROVED** [review]

**Review by nginnever — APPROVED** [review]
We would like to merge this commit with data encoding to multiSend()

**Pull request merged**
